/**
 * OUTERFIELDS Video Types
 *
 * Type definitions for video content, playback state, and streaming.
 */

/**
 * Video source information for streaming
 */
export interface VideoSource {
	/** Cloudflare Stream UID */
	streamUid: string;
	/** Direct playback URL (iframe embed) */
	playbackUrl: string;
	/** HLS manifest URL for adaptive streaming */
	hlsUrl: string;
	/** DASH manifest URL for adaptive streaming */
	dashUrl: string;
	/** Thumbnail image URL */
	thumbnailUrl: string;
	/** Animated thumbnail (if available) */
	animatedThumbnailUrl?: string;
}

/**
 * Video metadata
 */
export interface VideoMeta {
	/** Unique video identifier */
	id: string;
	/** Display title */
	title: string;
	/** Video description */
	description?: string;
	/** Duration in seconds */
	duration: number;
	/** Formatted duration string (e.g., "1h 15min") */
	durationFormatted: string;
	/** Category/series identifier */
	category: string;
	/** Episode number (if part of series) */
	episode?: string;
	/** Release year */
	year?: string;
	/** Content rating (e.g., "4.9") */
	rating?: string;
	/** View count */
	views?: string;
	/** Is new content */
	isNew?: boolean;
	/** Tags for filtering */
	tags?: string[];
}

/**
 * Complete video content item
 */
export interface VideoContent extends VideoMeta {
	/** Video streaming sources */
	source: VideoSource;
	/** Watch progress (0-100) */
	progress?: number;
	/** Last watched timestamp */
	lastWatched?: string;
	/** Is in user's watchlist */
	inWatchlist?: boolean;
}

/**
 * Video category/row for browsing
 */
export interface VideoCategory {
	/** Category identifier */
	id: string;
	/** Display title */
	title: string;
	/** Videos in this category */
	items: VideoContent[];
}

/**
 * Player state
 */
export interface PlayerState {
	/** Currently loaded video */
	video: VideoContent | null;
	/** Is playing */
	isPlaying: boolean;
	/** Current time in seconds */
	currentTime: number;
	/** Volume (0-1) */
	volume: number;
	/** Is muted */
	isMuted: boolean;
	/** Is fullscreen */
	isFullscreen: boolean;
	/** Is picture-in-picture */
	isPiP: boolean;
	/** Playback rate */
	playbackRate: number;
	/** Selected quality */
	quality: 'auto' | '1080p' | '720p' | '480p' | '360p';
	/** Is buffering */
	isBuffering: boolean;
	/** Buffer progress (0-100) */
	buffered: number;
	/** Captions enabled */
	captionsEnabled: boolean;
}

/**
 * Player controls interface
 */
export interface PlayerControls {
	play: () => void;
	pause: () => void;
	toggle: () => void;
	seek: (time: number) => void;
	seekRelative: (delta: number) => void;
	setVolume: (volume: number) => void;
	toggleMute: () => void;
	toggleFullscreen: () => void;
	togglePiP: () => void;
	setPlaybackRate: (rate: number) => void;
	setQuality: (quality: PlayerState['quality']) => void;
	toggleCaptions: () => void;
}

/**
 * Video analytics event
 */
export interface VideoAnalyticsEvent {
	type:
		| 'play'
		| 'pause'
		| 'seek'
		| 'complete'
		| 'progress'
		| 'quality_change'
		| 'fullscreen'
		| 'pip';
	videoId: string;
	timestamp: number;
	currentTime: number;
	duration: number;
	metadata?: Record<string, unknown>;
}

/**
 * Engagement heatmap data point
 */
export interface EngagementPoint {
	/** Time segment start (seconds) */
	start: number;
	/** Time segment end (seconds) */
	end: number;
	/** Engagement level (0-1) */
	engagement: number;
	/** Number of views in this segment */
	views: number;
	/** Rewatch count */
	rewatches: number;
}

/**
 * Video engagement data
 */
export interface VideoEngagement {
	videoId: string;
	totalViews: number;
	uniqueViewers: number;
	averageWatchTime: number;
	completionRate: number;
	heatmap: EngagementPoint[];
}

// ============================================
// Demo Content - Veo Generated Videos
// ============================================

/**
 * Demo video manifest structure (generated by Veo pipeline)
 */
export interface DemoVideoManifest {
	version: string;
	generatedAt: string;
	videos: Array<{
		id: string;
		title: string;
		category: string;
		duration: number;
		style: string;
		streamUid: string;
		playbackUrl: string;
		thumbnailUrl: string;
		dashUrl: string;
		hlsUrl: string;
		generatedAt: string;
	}>;
}

/**
 * Convert manifest entry to VideoContent
 */
export function manifestToVideoContent(
	entry: DemoVideoManifest['videos'][0],
	overrides?: Partial<VideoMeta>
): VideoContent {
	return {
		id: entry.id,
		title: entry.title,
		description: '',
		duration: entry.duration,
		durationFormatted: formatDuration(entry.duration),
		category: entry.category,
		source: {
			streamUid: entry.streamUid,
			playbackUrl: entry.playbackUrl,
			hlsUrl: entry.hlsUrl,
			dashUrl: entry.dashUrl,
			thumbnailUrl: entry.thumbnailUrl
		},
		...overrides
	};
}

/**
 * Format duration in seconds to human-readable string
 */
export function formatDuration(seconds: number): string {
	const hours = Math.floor(seconds / 3600);
	const minutes = Math.floor((seconds % 3600) / 60);

	if (hours > 0) {
		return `${hours}h ${minutes}min`;
	}
	return `${minutes} min`;
}

/**
 * Format current time for display (e.g., "1:23:45" or "23:45")
 */
export function formatTime(seconds: number): string {
	const h = Math.floor(seconds / 3600);
	const m = Math.floor((seconds % 3600) / 60);
	const s = Math.floor(seconds % 60);

	if (h > 0) {
		return `${h}:${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
	}
	return `${m}:${s.toString().padStart(2, '0')}`;
}
